apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: stealthhyy/myapi:v1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: MongoDbSettings__Host
          value: mongodb-service
        - name: MongoDbSettings__Password
          valueFrom:
            secretKeyRef:
              name: myapi-secrets
              key: mongodb-password
        livenessProbe:
          httpGet:
            path: /hc/live
            port: 80
        readinessProbe:
          httpGet:
            path: /hc/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  type: LoadBalancer
  selector:
    app: myapi
  ports:
    - port: 80
      targetPort: 80
